# This is a basic workflow to help you get started with Actions

name: Install

# Controls when the workflow will run
on:
#  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "install" ]
 # pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  install: 
   runs-on: ubuntu-latest
   steps:
     prerun:
       uses: @ittp/apps
         run: echo 1
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: apt
        run: sudo apt update && apt install curl wget tmate git cockpit -y >> index.html
     

      # Runs a set of commands using the runners shell
      - name: config
        run: |
          mkdir -p config
          echo "Date: \t $(date --utc) > config/date
          echo "powershell" > config/install
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          # Artifact name
          name: www/index.html # optional
          # Destination path
          path: ~/www/index.html # optional
        
      - name: HTML Preview
  # You may pin to the exact commit or the version.
  # uses: pavi2410/html-preview-action@9420cd81fbbe0035f59a39536ea5a0443daffa37
        uses: pavi2410/html-preview-action@v2
        with:
    # The HTML file you want to preview, relative to the root of the repo
      - name: HTML Preview
  # You may pin to the exact commit or the version.
  # uses: pavi2410/html-preview-action@9420cd81fbbe0035f59a39536ea5a0443daffa37
        uses: pavi2410/html-preview-action@v2
        with:
    # The HTML file you want to preview, relative to the root of the repo
          html_file: index.html # default is index.htmltml_file: # default is index.html
     - name: SSH Action
      # You may pin to the exact commit or the version.
      # uses: invi5H/ssh-action@ece33b57060e562f8d17b6c20b715de95204bbf2
      uses: invi5H/ssh-action@v1.0.0
      with:
        # A unique name for the server
        NAME: data # optional, default is server
        # The SSH username
        SSH_USER: git
        # The hostname or the IP address
        SSH_HOST: ittps.ru
        # The SSH port
        SSH_PORT: 22 # optional, default is 22
        # The full string SSH key
        SSH_KEY: git
